export const SAMPLE_BLOGS: Blog[] = [
    {
        id: '0',
        title: 'Find Your Skin Type',
        slug: 'find-your-skin-type',
        description: 'Take this short quiz to find your skin type!',
        image: 'new-placeholder-lg.png',
        topics: [],
        createdAt: 0,
        updatedAt: 0,
        content: '',
        type: 'products'
    },
    {
        id: '1',
        title: 'Ride or Die Beauty Products',
        slug: 'ride-or-die-beauty-products',
        description: 'These are my go-to products that I use on a daily basis.',
        image: 'blog-placeholder-1.png',
        topics: [],
        createdAt: 0,
        updatedAt: 0,
        content: '',
        type: 'products'
    },
    {
        id: '2',
        title: 'Basics of Eyeshadow',
        slug: 'basics-of-eyeshadow',
        description: 'Need some tips to level up your eyeshadow game?',
        image: 'blog-placeholder-2.png',
        topics: [],
        createdAt: 0,
        updatedAt: 0,
        content: '',
        type: 'tutorial'
    },
    {
        id: '3',
        title: 'Clean and Compact',
        slug: 'clean-and-compact',
        description: 'Channel your inner thrift-queen with these techniques!',
        image: 'blog-placeholder-3.png',
        topics: [],
        createdAt: 0,
        updatedAt: 0,
        content: '',
        type: 'lifestyle'
    },
    {
        id: '4',
        title: 'Basics of Contouring',
        slug: 'basics-of-contouring',
        description: 'A quick video showcasing my contouring techniques!',
        image: 'blog-placeholder-4.png',
        topics: [],
        createdAt: 0,
        updatedAt: 0,
        content: '',
        type: 'tutorial'
    },
    {
        id: '5',
        title: 'Wing it. Eyeliner, life, everything...',
        slug: 'wing-it-eyeliner-life-everything',
        description: 'Three easy ways to nail that wing.',
        image: 'blog-placeholder-5.png',
        topics: [],
        createdAt: 0,
        updatedAt: 0,
        content: '',
        type: 'lifestyle'
    },
    {
        id: '6',
        title: 'St.Sational',
        slug: 'st-sational',
        description: 'My honest review of Seint products.',
        image: 'blog-placeholder-6.png',
        topics: [],
        createdAt: 0,
        updatedAt: 0,
        content: '',
        type: 'products'
    },
]