export const SAMPLE_LOOKS: Look[] = [
    {
        id: '0',
        title: 'Thankful',
        slug: 'thankful',
        description: 'Today is a day to be thankful for all that we have.',
        image1: 'look-placeholder-lg.png',
        image2: 'look-placeholder-lg-2.png',
        colors: ['georgia', 'leo', 'ginger', 'coco'],
        tags: [],
        createdAt: 0,
        updatedAt: 0,
        content: ''
    },
    {
        id: '1',
        title: 'Ride or Die Beauty Products',
        slug: 'ride-or-die-beauty-products',
        description: 'These are my go-to products that I use on a daily basis.',
        image1: 'blog-placeholder-1.png',
        image2: 'blog-placeholder-1.png',
        colors: [],
        tags: [],
        createdAt: 0,
        updatedAt: 0,
        content: ''
    },
    {
        id: '2',
        title: 'Basics of Eyeshadow',
        slug: 'basics-of-eyeshadow',
        description: 'Need some tips to level up your eyeshadow game?',
        image1: 'blog-placeholder-2.png',
        image2: 'blog-placeholder-2.png',
        colors: [],
        tags: [],
        createdAt: 0,
        updatedAt: 0,
        content: ''
    },
    {
        id: '3',
        title: 'Clean and Compact',
        slug: 'clean-and-compact',
        description: 'Channel your inner thrift-queen with these techniques!',
        image1: 'blog-placeholder-3.png',
        image2: 'blog-placeholder-3.png',
        colors: [],
        tags: [],
        createdAt: 0,
        updatedAt: 0,
        content: ''
    },
    {
        id: '4',
        title: 'Basics of Contouring',
        slug: 'basics-of-contouring',
        description: 'A quick video showcasing my contouring techniques!',
        image1: 'blog-placeholder-4.png',
        image2: 'blog-placeholder-4.png',
        colors: [],
        tags: [],
        createdAt: 0,
        updatedAt: 0,
        content: ''
    },
    {
        id: '5',
        title: 'Wing it. Eyeliner, life, everything...',
        slug: 'wing-it-eyeliner-life-everything',
        description: 'Three easy ways to nail that wing.',
        image1: 'blog-placeholder-5.png',
        image2: 'blog-placeholder-5.png',
        colors: [],
        tags: [],
        createdAt: 0,
        updatedAt: 0,
        content: ''
    },
    {
        id: '6',
        title: 'St.Sational',
        slug: 'st-sational',
        description: 'My honest review of Seint products.',
        image1: 'blog-placeholder-6.png',
        image2: 'blog-placeholder-6.png',
        colors: [],
        tags: [],
        createdAt: 0,
        updatedAt: 0,
        content: ''
    }
]